version = 1
test_patterns = ["*/test/**"]

exclude_patterns = [
    "public/**,",
    "dist/**"
]  

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  module_system = "es-modules"
  environment = [
    "nodejs"
  ]
  dialect = "typescript"
  skip_doc_coverage = ["class-expression", "method-definition"]
